version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      npm-runtime:
        dependency-type: "production"
        update-types:
          - "patch"
          - "minor"
      npm-development:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker"
    directory: "/apps/smtp-shim"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
